# Generated by CMake, DO NOT EDIT
# Custom rules for obs-test
.SUFFIXES: 
all: \
	obs-test_buildpart_0

# obs-test_create_plugins_folder:	
# exist = $(shell if [ -d "/Users/zhiqiangwei/Work/openSource/obs-studio/obs-test/obs-plugins" ]; then echo 1; else echo 0; fi;)
#	ifeq (exist, 1)
#		echo "file is already existence"
#	else
#		mkdir ./obs-plugins
#	endif
	

obs-test_buildpart_0: 
	/usr/local/Cellar/cmake/3.18.4/bin/cmake -E copy \
	/Users/zhiqiangwei/Work/openSource/obs-studio/build/rundir/Debug/obs-plugins/* \
	/Users/zhiqiangwei/Work/openSource/obs-studio/obs-test/obs-plugins/
